---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: latest
  # require_chef_omnibus: 12.5.1
  # require_chef_omnibus: 11.18.14

provisioner:
  name: chef_zero

platforms:
# not supported :(
# https://github.com/chef/omnitruck/issues/77
#  - name: archlinux
#    driver:
#      box: 'terrywang/archlinux'
#    attributes:
#      system:
#        primary_interface: enp0s8
  - name: debian-8.6
    attributes:
      system:
        primary_interface: eth1
  - name: debian-7.11
    attributes:
      system:
        primary_interface: eth1
  - name: ubuntu-14.04
    attributes:
      system:
        primary_interface: eth1
  - name: ubuntu-12.04
    attributes:
      system:
        primary_interface: eth1
  - name: ubuntu-16.04
    attributes:
      system:
        primary_interface: enp0s8
  - name: centos-7.2
    attributes:
      system:
        primary_interface: enp0s8
  - name: centos-6.8
    attributes:
      system:
        primary_interface: eth1
  - name: fedora-24
    attributes:
      system:
        primary_interface: enp0s8
  - name: fedora-23
    attributes:
      system:
        primary_interface: enp0s8
  - name: freebsd-10.3
    attributes:
      system:
        primary_interface: em1
    driver_config:
        ssh:
          shell: '/bin/sh'
        network:
          - ["private_network", {ip: "172.16.172.16"}]
  - name: freebsd-9.3
    attributes:
      system:
        primary_interface: em1
    driver_config:
        ssh:
          shell: '/bin/sh'
        network:
          - ["private_network", {ip: "172.16.172.16"}]
suites:
  - name: default
    run_list:
     - recipe[system::default]
     - recipe[system::timezone]
     - recipe[system::install_packages]
     - recipe[system::uninstall_packages]
     - recipe[system::profile]
     - recipe[system::environment]
    driver:
      network:
      - ["private_network", {ip: "172.16.172.16"}]
    attributes:
      system:
        hostsfile_behaviour: create
        short_hostname: test
        domain_name: kitchen
        environment:
          extra:
           DINNER: Pizza
           DESERT: Ice cream
        timezone: Australia/Sydney
        static_hosts:
          95.211.29.66: supermarket.io
          184.106.28.82: chef.io
        packages:
          install:
           - "curl"
           - "wget"
          install_compile_time:
           - "sudo"
          uninstall:
           - "gcc"
        profile:
          append_scripts:
           - "export CHEF_IS_AWESOME=1"
           - "echo helloworld > /dev/null"
          path_prepend:
            - "/opt/local/food/bin"
          path_append:
            - "/opt/local/bin"
